workflow: test ldist

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -12,6 +12,9 @@ on:
 permissions:
   contents: read
 
+env:
+  PYTHONVER: 3.9
+
 jobs:
   build:
 
@@ -19,15 +22,28 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
-    - name: Set up Python 3.10
+    - name: Set up Python $PYTHONVER
       uses: actions/setup-python@v3
       with:
-        python-version: "3.9"
+        python-version: "$PYTHONVER"
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest praw dateutils pytz fuzzywuzzy python-Levenshtein lambda_setuptools
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+    - name: Check make
+      run: |
+        which make
+    - name: Full build
+      run: >-
+        export DISTUTILS_DEBUG=1;
+        for i in $$(seq 1 5); do
+          if python3 setup.py ldist --build-layer=True --layer-dir=python/lib/python$PYTHONVER/site-packages; then
+            echo "SUCCESS: lambda layer .zip created";
+            exit 0;
+          fi;
+        done;
+        echo "ERROR: all attempts failed"; exit 1
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
